config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'
  get 'static_pages/thanks'
  get 'static_pages/terms'
  get 'login'  => 'sessions#new' 
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users
end

app/models/admin.rb
class Admin < ApplicationRecord

	has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	validates :firstname, :lastname, :IDnum, :email, :terms, presence: true
	validates :IDnum, uniqueness: true
	validates :email, uniqueness: true

	has_many :projects
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	def create
		session[:user_id] = @user.id
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user 


	def current_user 
	  @current_user ||= Admin.find(session[:admin_id]) if session[:admin_id] 
	end

	def require_user 
  		redirect_to '/login' unless current_user 
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@admin = Admin.new
	end

	def create
		  @admin = Admin.find_by_username(params[:session][:username])
		  if @admin && @admin.authenticate(params[:session][:password_digest])
		    session[:admin_id] = @admin.id
		    redirect_to '/users'
		  else
		  	flash.now[:danger] = 'Invalid email/password combination'
		   	render 'new'
		  end 
	end

	def destroy 
		  session[:user_id] = nil 
		  redirect_to '/' 
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def thanks
  end

  def terms
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, only: [:index, :show]

	def index
		@user = User.all	
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)

		if @user.save
		      redirect_to '/static_pages/thanks'
   		 else
     		render 'new'
        end
	end


	private
		def user_params
				params.require(:user).permit(:firstname, :lastname, :email,
			:IDnum, :phone, :gender, :project, :terms)
		end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta  name = "viewport" content="width=device-width, initial-scale = 1" >
    <title><%= yield(:title) %> | Enactus VVU submit Idea </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/shared/_devise_flash.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info">
		<button type="button" class="close">
			&times;
		</button>
		<%= notice %>
	</div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-danger">
		<button type="button" class="close">
			&times;
		</button>
		<%= flash[:alert] %>
	</div>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>

    <div id="error_explanation">

      <div class="alert alert-danger" role="alert">
         <span style="font-size: 15px;"> <%= pluralize(object.errors.count, "error") %> prohibited this form from being sent. </span>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul>
          <% object.errors.full_messages.each do |msg| %>
            <li>
              <span style="font-size: 13px;"> <%= msg %> </span>
            </li>
          <% end %>
      </ul>
      </div>
    </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"> &times; </span>
          </button>
          <%= message %>
        </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
    <footer class="m-t-30">
        <div class="container">
            <ul class="list-inline">
                <li class="list-inline-item">
                    
                </li>
                <li class="footer-menu-divider list-inline-item"></li>
                <li class="list-inline-item">
                    
                </li>
                <li class="footer-menu-divider list-inline-item"></li>
                <li class="list-inline-item">
                    
                </li>
                <li class="footer-menu-divider list-inline-item"></li>
                <li class="list-inline-item">
                    
                </li>
                <li class="footer-menu-divider list-inline-item"></li>
                <li class="list-inline-item">
                    
                </li>
            </ul>
            <p class="copyright text-muted small text-center">
              <span class="text-white">&copy; 2017. Crafted by</span> <a href="https://polymathwhiz.github.io" target="_blank"><b>PolymathWhiz</b></a>
            </p>
        </div>
    </footer>

app/views/static_pages/terms.html.erb
<h3>
	Terms and Conditions
</h3>

<p>By accepting the terms and conditions, you agree to the following:</p>

<p>
	1.You will contribute to making this project a reality
</p>

<p>
	2.You will not take credit for this project, but will credit this project to Enactus Valley View (especially if we win the national expositon)
</p>

<p> 
	3.You will adhere to all Enactus Valley View and Enactus Ghana policies and guide lines 
</p>

app/views/static_pages/thanks.html.erb
<h1>Thanks for your submission!</h1>

app/views/users/_project.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/users/index.html.erb
<h1>User Projects</h1>
<br>
<table>
	<% @user.each do |user| %>
		<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
			<td class="list_description">
				<dl>
					<dt><%= user.IDnum %>  <%= user.firstname %> <%= user.lastname %></dt>
					<dd><%= truncate(strip_tags(user.project),
length: 80) %></dd>
				</dl>
			</td>
			<td class="list_actions">
				<%= link_to 'Show', user %><br/>
			</td>
		</tr>
	<% end %>
</table>

app/views/users/n.html.erb
<%=provide(:title, "Form")%>

<style>
  body {
    background-image: url('assets/bg.svg');
    background-size: cover;
  }
  
</style>
<h1>Create a New Article</h1>

<p>
	Welcome Enactus Valley View's project submission page
	Please submit your idea via the the form below
</p>

<h3>Best Of luck!</h3>

<%= form_for(@user) do |f| %>
	<p>
		<%=f.label :firstname %>
		<%=f.text_field :firstname %>
	</p>
	

	<p>
		<%=f.label :lastname %>
		<%=f.text_field :lastname %>
	</p>
	

	<p>
		<%=f.label :email %>
		<%=f.text_field :email %>
	</p>
	
	<p>
		<%=f.label :ID%>
		<%=f.text_field :IDnum %>
	</p>
	
	<p>
		<%=f.label :phone%>
		<%=f.text_field :phone %>
	</p>

    Project Idea
    <%= f.fields_for :project do |projects_form| %>
    	<p>
    		<%= projects_form.text_area :body %>
    	</p>
    	
    <% end %>

	<p>
		<%= f.submit :submit%>
	</p> 
<% end %>


<div class="form-group">
              <%= f.label :gender %>
              <%= f.select :title, options_for_select(gender_select), { prompt: "Select Gender" }, class: "form-control" %>
            </div>

app/views/users/new.html.erb
<style>
  body {
    background-image: url('assets/bg.svg');
    background-size: cover;
  }
</style>


<div class="container">
  <h2 class="text-center m-t-50 text-white">ENACTUS VVU </h2>
  <div class="row m-t-40">
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 25rem;">
        <div class="card-body">

          <%= form_for(@user) do |f| %>
          
            <div class="text-center">
              <h5 class="text-uppercase" style="margin-bottom: 2px;">Form</h4> <hr>
            </div> 

                           <% if @user.errors.any? %>
                <div id="error explanation">
                <div class="alert alert-error">
                The form contains <%= pluralize(@user.errors.count, "error") %>.
                </div>
                <ul>
                <% @user.errors.full_messages.each do |msg| %>
                <li> <%= msg %></li>
                <% end %>
                </ul>
                </div>
                <% end %>
           
            

              <div class="form-group">
                <%=f.label :firstname %>
                <%= f.text_field :firstname, class: 'form-control', placeholder: 'Miracle' %>
              </div>

               <div class="form-group">
                <%=f.label :lastname%>
                <%= f.text_field :lastname, class: 'form-control', placeholder: 'Ceesay' %>
              </div>

            <div class="form-group">
              <%= f.label :gender %>
              <%= f.select :gender, options_for_select(["male","female"]), { prompt: "Select Gender" }, class: "form-control" %>
            </div>
                
            <div class="form-group">
              <%= f.label :IDnum %>
              <%= f.text_field :IDnum, class: 'form-control', placeholder: '218CS01003883' %>
            </div>

            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control', placeholder: 'anyanwumiracle78@gmail.com' %>
            </div>

            <div class="form-group">
              <%= f.label :phone %>
              <%= f.text_field :phone, class: 'form-control', placeholder: '0509289409' %>
            </div>
            
            <div class="form-group">
              <%= f.label :project %>
              <%= f.text_area :project, class: 'form-control' %>
            </div>
            
            <div class="form-group">
            <p> 
            <%=f.check_box :terms%>
              I Accept
              <%= link_to 'Terms and conditions', static_pages_terms_path%>
            </p>
              
            </div>


            <%= f.submit "Submit", class: 'btn btn-success btn-block' %>
            <% end %>
            </div>
          </div>
        </div>
    </div>
  </div>

</div>           
                

app/views/users/show.html.erb
<h3><%= @user.IDnum %>  <%= @user.firstname %> <%= @user.lastname %></h3>

<p>
	<%=@user.project%>
</p>